
set(GCOV_C_FLAGS "--coverage -Wall -Werror -g -O0")
set(GCOV_LINK_FLAGS "--coverage -g -O0")

set(CMAKE_CXX_FLAGS 
	"${CMAKE_C_FLAGS} ${GCOV_C_FLAGS}"
	CACHE STRING "" FORCE
)

set(CMAKE_C_FLAGS 
	"${CMAKE_C_FLAGS} ${GCOV_C_FLAGS}"
	CACHE STRING "" FORCE
)

set(CMAKE_EXE_LINKER_FLAGS
	"${CMAKE_EXE_LINKER_FLAGS} ${GCOV_LINK_FLAGS}"
	CACHE STRING "" FORCE
)
set(CMAKE_C_STANDARD 99)
