
// This file has been generated by the GUI designer. Do not modify.
namespace covgtk
{
	public partial class CloserTabLabel
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label;
		private global::Gtk.Button closer;
		private global::Gtk.Image image1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget covgtk.CloserTabLabel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "covgtk.CloserTabLabel";
			// Container child covgtk.CloserTabLabel.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.hbox1.Add (this.label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label]));
			w1.Position = 0;
			w1.Padding = ((uint)(2));
			// Container child hbox1.Gtk.Box+BoxChild
			this.closer = new global::Gtk.Button ();
			this.closer.CanFocus = true;
			this.closer.Name = "closer";
			this.closer.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child closer.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			this.closer.Add (this.image1);
			this.closer.Label = null;
			this.hbox1.Add (this.closer);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.closer]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
