
// This file has been generated by the GUI designer. Do not modify.
namespace XR.Baboon
{
	public partial class AssemblyItem
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label assemblyName;
		private global::Gtk.Label sourceFolderPath;
		private global::Gtk.FileChooserButton newFolderPath;
		private global::Gtk.HSeparator hseparator1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XR.Baboon.AssemblyItem
			global::Stetic.BinContainer.Attach (this);
			this.Name = "XR.Baboon.AssemblyItem";
			// Container child XR.Baboon.AssemblyItem.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.assemblyName = new global::Gtk.Label ();
			this.assemblyName.Name = "assemblyName";
			this.assemblyName.Xpad = 3;
			this.assemblyName.Ypad = 3;
			this.assemblyName.Xalign = 0F;
			this.assemblyName.LabelProp = global::Mono.Unix.Catalog.GetString ("Foo.Bar.Baz.AssemblyName");
			this.assemblyName.UseMarkup = true;
			this.assemblyName.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.vbox3.Add (this.assemblyName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.assemblyName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.sourceFolderPath = new global::Gtk.Label ();
			this.sourceFolderPath.Name = "sourceFolderPath";
			this.sourceFolderPath.Xpad = 5;
			this.sourceFolderPath.Ypad = 2;
			this.sourceFolderPath.Xalign = 0F;
			this.sourceFolderPath.LabelProp = global::Mono.Unix.Catalog.GetString ("/home/foo/bar/baz/path/to/my/assembly/source/folder/blaa/basfdasdasdfasd/sdfsdfsdf/sdf/sdf/fsdfsd");
			this.sourceFolderPath.UseMarkup = true;
			this.sourceFolderPath.Ellipsize = ((global::Pango.EllipsizeMode)(1));
			this.vbox3.Add (this.sourceFolderPath);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.sourceFolderPath]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.newFolderPath = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Folder"), ((global::Gtk.FileChooserAction)(2)));
			this.newFolderPath.Name = "newFolderPath";
			this.vbox3.Add (this.newFolderPath);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.newFolderPath]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox3.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator1]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
