
// This file has been generated by the GUI designer. Do not modify.
namespace XR.Baboon
{
	public partial class MainWindow
	{
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView itemtree;
		private global::Gtk.Notebook notebook1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XR.Baboon.MainWindow
			this.Name = "XR.Baboon.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 700;
			this.DefaultHeight = 440;
			// Container child XR.Baboon.MainWindow.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 240;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.itemtree = new global::Gtk.TreeView ();
			this.itemtree.CanFocus = true;
			this.itemtree.Name = "itemtree";
			this.itemtree.EnableSearch = false;
			this.itemtree.HeadersVisible = false;
			this.GtkScrolledWindow.Add (this.itemtree);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = -1;
			this.notebook1.Scrollable = true;
			this.notebook1.BorderWidth = ((uint)(3));
			this.hpaned1.Add (this.notebook1);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.itemtree.RowActivated += new global::Gtk.RowActivatedHandler (this.OnItemtreeRowActivated);
		}
	}
}
