
// This file has been generated by the GUI designer. Do not modify.
namespace XR.Baboon
{
	public partial class SourceHeaderBlock
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label heading;
		
		private global::Gtk.Label subheading;
		
		private global::Gtk.ProgressBar percentage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget XR.Baboon.SourceHeaderBlock
			global::Stetic.BinContainer.Attach (this);
			this.Name = "XR.Baboon.SourceHeaderBlock";
			// Container child XR.Baboon.SourceHeaderBlock.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 4;
			// Container child vbox1.Gtk.Box+BoxChild
			this.heading = new global::Gtk.Label ();
			this.heading.Name = "heading";
			this.heading.Xpad = 3;
			this.heading.Xalign = 0F;
			this.heading.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size=\"large\">File.cs</span>");
			this.heading.UseMarkup = true;
			this.heading.Wrap = true;
			this.heading.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.vbox1.Add (this.heading);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.heading]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(1));
			// Container child vbox1.Gtk.Box+BoxChild
			this.subheading = new global::Gtk.Label ();
			this.subheading.Name = "subheading";
			this.subheading.Xpad = 3;
			this.subheading.Xalign = 0F;
			this.subheading.LabelProp = global::Mono.Unix.Catalog.GetString ("subheading");
			this.subheading.Wrap = true;
			this.subheading.Ellipsize = ((global::Pango.EllipsizeMode)(3));
			this.vbox1.Add (this.subheading);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.subheading]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.percentage = new global::Gtk.ProgressBar ();
			this.percentage.Name = "percentage";
			this.percentage.Text = global::Mono.Unix.Catalog.GetString ("31%");
			this.percentage.Fraction = 0.31;
			this.vbox1.Add (this.percentage);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.percentage]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			w3.Padding = ((uint)(1));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
